Repository idx-academy/mic-orders, pull requests merged in 2024-07, with the labels that each got.

#100 Implemented endpoint for adding products to the cart.
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/controller/CartItemController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/ErrorHandlerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseUseCaseTest.java
  code/orders-boot/src/main/resources/db/migration/V1.13__createCartItemsTable.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/account/exception/AccountNotFoundException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/entity/CartItem.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/entity/CreateCartItemDTO.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/CreateCartItemByUserUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/exception/ProductNotFoundException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/CartItemMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/entity/CartItemEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/entity/CartItemId.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: back-end, Sprint 2

#102 Added use case to get user details from authentication
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/api/template/api.mustache
  code/orders-api-rest/api/template/beanValidationCore.mustache
  code/orders-api-rest/pom.xml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/annotation/AllowedAccountId.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/controller/AuthTokenController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/validator/AccountIdValidator.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/auth/controller/AuthTokenControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/auth/validator/AccountIdValidatorTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/ErrorHandlerTest.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/security/SecurityUser.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/GetAccountDetailsUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/entity/CartItemId.java
Labels: back-end, Sprint 2

#107 Improved code of "add product to th cart" and " place order" endpoints
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestConstants.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestSecurityUtil.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/auth/controller/AuthTokenControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/auth/validator/AccountIdValidatorTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-application/pom.xml
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseImpl.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SwaggerConfig.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/CartItemMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
Labels: back-end, Sprint 2

#113 Added token claim description
  code/orders-api-rest/api/openapi-rest.yml
Labels: documentation, back-end, Sprint 2

#115 changed logic of increasing product quantity to throw exception when …
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/exception/CartItemAlreadyExists.java
Labels: bug, back-end, Sprint 2

#117 Improve mutation coverage of tests
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/ChangeQuantityUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseTest.java
Labels: back-end, Sprint 2, test

#121 Changed authorities for place and get orders
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/validator/CheckAccountIdUseCaseImpl.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersController.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
Labels: bug, back-end, Sprint 2

#123 Added integration getOrdersHistoryByUserId tests
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrdersHistoryByUserId.feature
  e2e/karate/src/test/resources/karate-auth.js
Labels: back-end, Sprint 2, karate-test

#127 Feature/111/implement endpoint which remove product form cart
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/controller/CartItemController.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestConstants.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/DeleteProductFromCartUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/DeleteProductFromCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/exception/CartItemNotFoundException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/DeleteProductFromCartUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
Labels: back-end, Sprint 3

#138 Bug 128 add total field for order response
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/controller/CartItemController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/mapper/OrderDTOMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/mapper/PageOrderDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CalculateOrderTotalPriceUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/CalculatePriceUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CalculateOrderTotalPriceUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/CalculatePriceUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/entity/Order.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/usecase/CalculateOrderTotalPriceUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/CalculatePriceUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/OrderMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/OrderPageMapper.java
Labels: bug, back-end, open-api specification, Sprint 3

#141 (140) Create MANAGER role
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestConstants.java
  code/orders-boot/src/main/resources/db/migration/V1.15__addManager.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/account/entity/enumerated/Role.java
Labels: back-end, Sprint 3

#142 (136) Implemented endpoint for getting cart items
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/controller/CartItemController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/mapper/CartItemDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/GetCartItemsUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/CalculatePriceUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/GetCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/CalculatePriceUseCaseTest.java
  code/orders-boot/src/test/java/com/academy/orders/boot/config/security/UserDetailsServiceTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/dto/CartItemDto.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/dto/CartResponseDto.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/entity/CartItem.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/GetCartItemsUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/CalculatePriceUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/CartItemMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderEntity.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
Labels: back-end, Sprint 3

#146 Added karate tests to cart endpoints and cucumber report
  e2e/karate/pom.xml
  e2e/karate/src/test/java/com/academy/orders/karate/KarateRunnerTest.java
  e2e/karate/src/test/java/com/academy/orders/karate/generator/DataGenerator.java
  e2e/karate/src/test/resources/apis/orders/features/auth/authorization.feature
  e2e/karate/src/test/resources/apis/orders/features/cart/cart.feature
  e2e/karate/src/test/resources/apis/orders/helpers/getProductId.feature
  e2e/karate/src/test/resources/config-local-secrets.yml
  e2e/karate/src/test/resources/karate-auth.js
Labels: back-end, karate-test, Sprint 3

#150 Improved addManager.sql script
  code/orders-boot/src/main/resources/db/migration/V1.15__addManager.sql
Labels: bug, back-end, Sprint 3

#153 Changed test method names
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/cart/controller/CartItemController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersController.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/mapper/LocalDateTimeMapperTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/mapper/OrderStatusMapperTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/mapper/ProductPreviewDTOMapperTest.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/DeleteProductFromCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/GetCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/ChangeQuantityUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CreateOrderUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/CalculatePriceUseCaseTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/PageableMapperTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: back-end, Sprint 3

#160 Added new products to DB
  code/orders-boot/src/main/resources/db/migration/V1.16__addNewProducts.sql
  code/orders-boot/src/main/resources/db/migration/V1.17__addSomeProductToUserCart.sql
Labels: back-end, Sprint 3, products

#163 Fixed clean code issues
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersManagementControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CalculateOrderTotalPriceUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CalculateOrderTotalPriceUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetAllOrdersUseCaseTest.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/PageableMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepository.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
Labels: back-end, Sprint 3

#165 Fixed hibernate warning on get orders history endpoint
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderJpaAdapter.java
Labels: bug, back-end, Sprint 3

#167 Changed CustomOrderRepository to set max results to 1
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepository.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
Labels: bug, back-end, Sprint 3

#170 Implement karate tests to create order feature
  e2e/karate/pom.xml
  e2e/karate/src/test/java/com/academy/orders/karate/db/DbUtils.java
  e2e/karate/src/test/resources/apis/orders/features/auth/testSignIn.feature
  e2e/karate/src/test/resources/apis/orders/features/auth/testSignUp.feature
  e2e/karate/src/test/resources/apis/orders/features/cart/testAddProductToCart.feature
  e2e/karate/src/test/resources/apis/orders/features/cart/testDeleteProductFromBucket.feature
  e2e/karate/src/test/resources/apis/orders/features/cart/testGetCartElements.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testCreateOrder.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrderById.feature
  e2e/karate/src/test/resources/apis/orders/test-data/createOrderRequest.json
  e2e/karate/src/test/resources/config-local-secrets.yml
  e2e/karate/src/test/resources/karate-config.js
Labels: back-end, karate-test, Sprint 3

#176 Fixed dublicate endpoints in swagger
  code/orders-api-rest/api/openapi-rest.yml
  e2e/karate/src/test/resources/apis/orders/features/orders/testUpdateOrderStatus.feature
Labels: bug, back-end, Sprint 3

#169 Add karate tests for get all orders
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrdersHistoryByUserId.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testManagementOrders.feature
  e2e/karate/src/test/resources/apis/orders/test-data/page_200.json
  e2e/karate/src/test/resources/apis/orders/test-data/response_4xx.json
Labels: back-end, karate-test, Sprint 3

#180 Edited product status
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductPreviewDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-boot/src/main/resources/db/migration/V1.19__updateProductStatuses.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/product/entity/enumerated/ProductStatus.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
  e2e/karate/src/test/resources/config-local.yml
Labels: bug, back-end, Sprint 4

#181 Added json for creation of the image mock server
  code/orders-boot/src/test/resources/compose/mocks/mappings/get_v1_images.json
Labels: back-end, Sprint 4

#185 Update product status endpoint
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsManagementController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductStatusDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/TestSecurityConfig.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsManagementControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/UpdateStatusUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/UpdateStatusUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/UpdateStatusUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: back-end, Sprint 4

#187 Added specification for "Get all products for manager endpoint"
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/PageableMapper.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/PageableMapperTest.java
Labels: back-end, Sprint 4, feature

#189 Implemented "Get all products for manager" endpoint
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/mapper/LocalDateTimeMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsManagementController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ManagementProductMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductPreviewDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsManagementControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetManagerProductsUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetManagerProductsUseCaseImplTest.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/MapperConfig.java
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/controller/OrdersControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/product/controller/ProductManagementControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/AbstractRepository.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-boot/src/test/resources/application-it.yml
  code/orders-domain/src/main/java/com/academy/orders/domain/product/dto/ProductManagementFilterDto.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/entity/enumerated/ProductStatus.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetManagerProductsUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/PageableMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductPageMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductTranslationMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/PageableMapperTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: back-end, Sprint 4, feature

#191 Сonfigured integration and added required dependencies
  code/orders-api-rest-clients/colors-api/api/openapi-rest.yml
  code/orders-boot/src/main/java/com/academy/orders/boot/config/rest/ImagesApiClientConfiguration.java
  code/orders-boot/src/main/resources/application.yml
  code/orders-infrastructure/pom.xml
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/pom.xml
Labels: back-end, Sprint 4, feature, integration

#192 Implement get order by id endpoint
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersManagementController.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersManagementControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetAllOrdersUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetAllOrdersUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/usecase/GetOrderByIdUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepository.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
Labels: back-end, Sprint 4, feature

#195 Add karate tests for patch product status
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsManagementControllerTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/UpdateStatusUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetAllOrders.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testUpdateOrderStatus.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testUpdateProductStatus.feature
Labels: documentation, back-end, karate-test, products, Sprint 4

#196 Edited karate test for get order by id
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrderById.feature
  e2e/karate/src/test/resources/apis/orders/test-data/getOrderById_200.json
Labels: back-end, karate-test, Sprint 4

#197 Changed query from native to jpql
  code/orders-boot/src/main/resources/db/migration/V1.20__updateProductStatuses.sql
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
Labels: bug, back-end, Sprint 4

#202 Refactored code to use UK lang code instead of UA
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestConstants.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/cart/controller/CartItemControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersManagementControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsManagementControllerTest.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/TestConstants.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/GetCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetAllOrdersUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetManagerProductsUseCaseImplTest.java
  code/orders-boot/src/main/resources/db/migration/V1.21__updateUaLangCodeToUk.sql
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/product/controller/ProductManagementControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
Labels: bug, back-end, Sprint 4

#203 Implemented tests to "Get products for manager" endpoint.
  e2e/karate/src/test/resources/apis/orders/features/products/testGetAllManagerProducts.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testUpdateProductStatus.feature
  e2e/karate/src/test/resources/apis/orders/helpers/getProductId.feature
  e2e/karate/src/test/resources/config-local-secrets.yml
  e2e/karate/src/test/resources/config-local.yml
  e2e/karate/src/test/resources/karate-config.js
Labels: back-end, karate-test, Sprint 4

#207 Fixed no session bug
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
Labels: bug, back-end

#208 Added third-party
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/UpdateOrderStatusUseCaseImpl.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/CacheConfig.java
  code/orders-boot/src/main/resources/application.yml
  code/orders-boot/src/main/resources/db/migration/V1.22__updateProductImageLinks.sql
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/AbstractRepository.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-boot/src/test/resources/application-it.yml
  code/orders-domain/src/main/java/com/academy/orders/domain/common/respository/ImageRepository.java
  code/orders-infrastructure/pom.xml
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/repository/ImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/repository/ImageRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
  code/pom.xml
Labels: back-end, Sprint 4, feature

#211 Reverted using of third party
  code/orders-boot/src/main/resources/db/migration/V1.23__addUrlToProductsNames.sql
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: bug, back-end

#218 Changed get all visible products query
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
Labels: bug, back-end, Sprint 4

#240 Added integration to getAllProducts endpoint
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseTest.java
  code/orders-domain/src/main/java/com/academy/orders/domain/common/Page.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/entity/Product.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductImageRepository.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductImageRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: bug, back-end, Sprint 5

#242 Edited pagination for get all orders endpoint
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepository.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
Labels: bug, back-end, Sprint 5

#243 Implemeted endpoint for blocking/unblocking users
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/accounts/controller/AccountsManagementController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/accounts/mapper/AccountDTOMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/accounts/controller/AccountsManagementControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/ErrorHandlerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/account/usecase/ChangeAccountStatusUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/account/usecase/ChangeAccountStatusUseCaseImplTest.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SecurityConfig.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/security/UserDetailsServiceImpl.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/AbstractRepository.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/repository/AccountRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/ChangeAccountStatusUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/account/repository/AccountRepositoryImplTest.java
Labels: back-end, feature, Sprint 5

#244 Feature 238 product search
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/PageProductSearchResultDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/TestConstants.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/mapper/UpdateOrderStatusRequestDTOMapperTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetProductSearchResultsUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetProductSearchResultsUseCaseTest.java
  code/orders-boot/src/main/resources/db/migration/V1.24__addFullTextIndexForProductsTranslations.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/common/Page.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductImageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetProductSearchResultsUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductPageMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductTranslationMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/ProductMapperTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
  e2e/karate/src/test/resources/apis/orders/features/products/testGetAllProducts.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testSearchProducts.feature
  e2e/karate/src/test/resources/apis/orders/test-data/productSearchResults_200.json
Labels: back-end, feature, Sprint 5
