Repository idx-academy/mic-orders, pull requests merged in 2024-06, with the labels that each got.

#51 Feature 38 implement new openapi specification
  .gitignore
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/AuthTokenController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SecurityConfig.java
  code/orders-boot/src/test/java/com/academy/orders/apirest/common/AbstractControllerIT.java
Labels: documentation, Sprint 0, back-end

#55 Added security using database
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/pom.xml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/controller/AuthTokenController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/auth/mapper/SignUpRequestDTOMapper.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/contoller/OrdersController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/mapper/OrderDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/auth/controller/AuthTokenControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/TestSecurityConfig.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/account/usecase/CreateUserAccountUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/account/usecase/CreateUserAccountUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseTest.java
  code/orders-boot/src/main/java/com/academy/orders/boot/Application.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/DatasourceConfiguration.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SecurityConfig.java
  code/orders-boot/src/main/java/com/academy/orders/boot/security/SecurityUser.java
  code/orders-boot/src/main/java/com/academy/orders/boot/security/UserDetailsServiceImpl.java
  code/orders-boot/src/main/resources/application-local.yml
  code/orders-boot/src/main/resources/db/migration/V1.1__createAccountsTable.sql
  code/orders-boot/src/main/resources/db/migration/V1.2__addDefaultUsers.sql
  code/orders-boot/src/test/java/com/academy/orders/ModelsUtil.java
  code/orders-boot/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/security/UserDetailsServiceTest.java
  code/orders-boot/src/test/resources/application-it.yml
  code/orders-domain/src/main/java/com/academy/orders/domain/account/entity/Account.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/entity/CreateAccountDTO.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/entity/enumerated/Role.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/entity/enumerated/UserStatus.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/exception/AccountAlreadyExistsException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/repository/AccountRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/CreateUserAccountUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/exception/AlreadyExistsException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/exception/NotFoundException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/entity/Order.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/exception/OrderNotFoundException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/usecase/GetOrderByIdUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/usecase/GetOrderByIdUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/AccountMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/entity/AccountEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/OrderMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/pom.xml
  e2e/karate/src/test/resources/config-local-secrets.yml
  e2e/karate/src/test/resources/karate-auth.feature
Labels: Sprint 1, back-end

#63 Test 61 add karate signup tests
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/common/AbstractControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/controller/OrdersControllerIT.java
  e2e/karate/pom.xml
  e2e/karate/src/test/java/com/academy/orders/karate/helper/DataGenerator.java
  e2e/karate/src/test/resources/apis/orders/features/auth/authorization.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrderById.feature
  e2e/karate/src/test/resources/apis/orders/test-data/getOrderById_200.json
  e2e/karate/src/test/resources/apis/orders/test-data/signup-request.json
Labels: Sprint 1, back-end, karate-test

#66 Implemented tests to ErrorHandler class
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/ErrorHandler.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/common/ErrorHandlerTest.java
Labels: Sprint 1, back-end, test

#75 Updated validation and readme documentation
  README.md
  code/orders-api-rest/api/openapi-rest.yml
Labels: documentation, Sprint 1, back-end

#82 added placeOrder endpoint to openapi-rest.yml file
  code/orders-api-rest/api/openapi-rest.yml
Labels: back-end, Sprint 2, open-api specification

#85 Improved karate tests
  e2e/karate/src/test/resources/apis/orders/features/auth/authorization.feature
Labels: bug, back-end, Sprint 2, karate-test

#91 Implemented order essence entities.
  code/orders-boot/src/main/resources/db/migration/V1.10__createTableOrderItems.sql
  code/orders-boot/src/main/resources/db/migration/V1.11__createPostAddressesTable.sql
  code/orders-boot/src/main/resources/db/migration/V1.9__createProductTable.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/order/entity/enumerated/DeliveryMethod.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/entity/enumerated/OrderStatus.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/entity/AccountEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderItemEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderItemId.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/OrderReceiverVO.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/entity/PostAddressEntity.java
Labels: back-end, Sprint 2

#92 Added openapi specifications for user's order history with pagination
  code/orders-api-rest/api/openapi-rest.yml
Labels: documentation, back-end, Sprint 2

#94 Reverted cors configuration to default
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SecurityConfig.java
  code/orders-boot/src/main/resources/application.yml
Labels: back-end

#96 Added domains and generic mappers for pagination
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/common/mapper/PageableDTOMapper.java
  code/orders-domain/src/main/java/com/academy/orders/domain/common/Page.java
  code/orders-domain/src/main/java/com/academy/orders/domain/common/Pageable.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/PageableMapper.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/PageableMapperTest.java
Labels: back-end, Sprint 2

#95 added sql file to remove is_paid colum from order_item table.
  code/orders-boot/src/main/resources/db/migration/V1.12__removeIsPaidColumFromOrderItemsTable.sql
Labels: bug, back-end
