Repository idx-academy/mic-orders, pull requests merged in 2024-08, with the labels that each got.

#251 Add filter by tags for "get products", changed setting for mock server, added integration tests
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductPreviewDTOMapper.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/accounts/controller/AccountsManagementControllerTest.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/products/controller/ProductsControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseTest.java
  code/orders-boot/pom.xml
  code/orders-boot/src/main/java/com/academy/orders/boot/config/security/UserDetailsServiceImpl.java
  code/orders-boot/src/main/resources/application.yml
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/account/controller/AccountsManagementControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/apirest/orders/common/AbstractControllerIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/config/security/UserDetailsServiceTest.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/account/AccountRepositoryIT.java
  code/orders-boot/src/test/resources/compose/mocks/mappings/get_v1_images.json
  code/orders-domain/src/main/java/com/academy/orders/domain/account/repository/AccountRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetAllProductsUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/account/repository/AccountRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/account/repository/AccountRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
  code/pom.xml
Labels: back-end, test, feature, integration, Sprint 5

#254 Fixed count query for "get all products" endpoint
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
Labels: bug, back-end, Sprint 5

#255 Integration tests for order repository
  code/orders-boot/src/main/resources/db/migration/V1.25__addOrdersForDefaultUser.sql
  code/orders-boot/src/test/java/com/academy/orders/ModelUtils.java
  code/orders-boot/src/test/java/com/academy/orders/ModelsUtil.java
  code/orders-boot/src/test/java/com/academy/orders/boot/config/security/UserDetailsServiceTest.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/account/repository/AccountRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/repository/AbstractRepository.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/order/repository/OrderRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
Labels: back-end, test, Sprint 5

#259 Add admin authorities to all endpoints
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersManagementController.java
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsManagementController.java
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetAllOrders.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrderById.feature
Labels: back-end, Sprint 5

#264 Updated order table
  code/orders-boot/src/main/resources/db/migration/V1.26__updateUserForDefaultOrders.sql
Labels: bug, back-end, Sprint 5

#263 IT tests to Account and CartItem repositories
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/controller/ProductsManagementController.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/account/repository/AccountRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/cart/repository/CartItemRepositoryIT.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/repository/AccountRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemRepository.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemRepositoryImplTest.java
Labels: back-end, test, integration, Sprint 5

#270 Refactored karate tests
  e2e/karate/src/test/resources/apis/orders/features/auth/testSignUp.feature
  e2e/karate/src/test/resources/apis/orders/features/cart/testGetCartElements.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testCreateOrder.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetAllOrders.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrderById.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testGetOrdersHistoryByUserId.feature
  e2e/karate/src/test/resources/apis/orders/features/orders/testUpdateOrderStatus.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testSearchProducts.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testUpdateProductStatus.feature
  e2e/karate/src/test/resources/apis/orders/test-data/requests/createOrderRequest.json
  e2e/karate/src/test/resources/apis/orders/test-data/requests/signupRequest.json
  e2e/karate/src/test/resources/apis/orders/test-data/responses/getCartItemsResponse.json
  e2e/karate/src/test/resources/apis/orders/test-data/responses/getOrderById_200.json
  e2e/karate/src/test/resources/apis/orders/test-data/responses/page_200.json
  e2e/karate/src/test/resources/apis/orders/test-data/responses/productSearchResults_200.json
  e2e/karate/src/test/resources/apis/orders/test-data/responses/response_4xx.json
  e2e/karate/src/test/resources/config-local-secrets.yml
  e2e/karate/src/test/resources/karate-auth.js
Labels: back-end, karate-test, Sprint 5

#272 Cancel an order endpoint
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/orders/controller/OrdersController.java
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/orders/controller/OrdersControllerTest.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/CancelOrderUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CancelOrderUseCaseTest.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/order/repository/OrderRepositoryIT.java
  code/orders-domain/src/main/java/com/academy/orders/domain/exception/PaidException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/exception/InsufficientProductQuantityException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/exception/InvalidOrderStatusTransitionException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/exception/OrderFinalStateException.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/usecase/CancelOrderUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
  e2e/karate/src/test/resources/apis/orders/features/orders/testCancelOrder.feature
Labels: back-end, feature, Sprint 5

#274 Feature 265 add email filter param
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-api-rest/src/test/java/com/academy/orders/apirest/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-boot/src/main/resources/db/migration/V1.27__addIndexForOrdersEmail.sql
  code/orders-domain/src/main/java/com/academy/orders/domain/order/dto/OrdersFilterParametersDto.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepository.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/ModelUtils.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/CustomOrderRepositoryTest.java
Labels: back-end, feature, Sprint 5

#284 Edited queries for orders and products
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: bug, back-end, Sprint 5

#285 Bug wrong account id
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/order/repository/OrderRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  e2e/karate/src/test/resources/apis/orders/features/orders/testUpdateOrderStatus.feature
Labels: bug, back-end, Sprint 5

#287 Feature 286 recomended sort for products
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/UpdateOrderStatusUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/CancelOrderUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseTest.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/repository/ProductRepository.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/entity/ProductEntity.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductImageRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
Labels: back-end, feature, Sprint 5

#292 Bug 291 sort products by name
  code/orders-api-rest/api/openapi-rest.yml
  code/orders-boot/src/test/java/com/academy/orders/boot/TestConstants.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductJpaAdapter.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImplTest.java
  e2e/karate/src/test/resources/apis/orders/features/products/testGetAllProducts.feature
Labels: bug, back-end, Sprint 5

#293 Added third-party integration to all endpoints which are retuning images.
  code/orders-api-rest/src/main/java/com/academy/orders/apirest/products/mapper/ProductMapper.java
  code/orders-application/src/main/java/com/academy/orders/application/cart/usecase/GetCartItemsUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/CreateProductUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/ExtractNameFromUrlUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetManagerProductsUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetProductByIdUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/GetProductDetailsByIdUseCaseImpl.java
  code/orders-application/src/main/java/com/academy/orders/application/product/usecase/UpdateProductUseCaseImpl.java
  code/orders-application/src/test/java/com/academy/orders/application/ModelUtils.java
  code/orders-application/src/test/java/com/academy/orders/application/TestConstants.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/CreateCartItemByUserUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/cart/usecase/GetCartUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/ChangeQuantityUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrderByIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/order/usecase/GetOrdersByUserIdUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/CreateProductUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/ExtractNameFromUrlUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetAllProductsUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetManagerProductsUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetProductByIdUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetProductDetailsByIdUseCaseImplTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/GetProductSearchResultsUseCaseTest.java
  code/orders-application/src/test/java/com/academy/orders/application/product/usecase/UpdateProductUseCaseImplTest.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/CacheConfig.java
  code/orders-boot/src/main/java/com/academy/orders/boot/config/SecurityConfig.java
  code/orders-boot/src/main/resources/application.yml
  code/orders-boot/src/main/resources/db/migration/V1.28__updateProductsImages.sql
  code/orders-boot/src/test/resources/compose/mocks/mappings/get_v1_images.json
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemImageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/common/Page.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/entity/enumerated/OrderStatus.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderImageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/ExtractNameFromUrlUseCase.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/CartItemMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/cart/repository/CartItemImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/repository/ImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/OrderMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/order/repository/OrderImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/ProductMapper.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductImageRepositoryImpl.java
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/product/repository/ProductRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/cart/repository/CartItemImageRepositoryImplTest.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/order/repository/OrderImageRepositoryImplTest.java
Labels: back-end, feature, integration, Sprint 5

#294 Test/267 268/karate and integration tests
  code/orders-api-rest-clients/images-api/api/openapi-rest.yml
  code/orders-api-rest-clients/images-api/pom.xml
  code/orders-boot/src/main/java/com/academy/orders/boot/config/rest/ImagesApiClientConfiguration.java
  code/orders-boot/src/test/java/com/academy/orders/ModelUtils.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/account/repository/AccountRepositoryITIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/cart/repository/CartImageRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/cart/repository/CartItemRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/repository/AbstractRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/common/repository/ImageRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/order/repository/OrderImageRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/order/repository/OrderRepositoryITIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/product/repository/ProductRepositoryIT.java
  code/orders-boot/src/test/resources/application-it.yml
  code/orders-infrastructure/pom.xml
  code/orders-infrastructure/src/main/java/com/academy/orders/infrastructure/common/repository/ImageRepositoryImpl.java
  code/orders-infrastructure/src/test/java/com/academy/orders/infrastructure/common/repository/ImageRepositoryImplTest.java
  code/pom.xml
  e2e/karate/src/test/resources/apis/orders/features/accounts/changeStatusOfAccount.feature
  e2e/karate/src/test/resources/apis/orders/features/products/testUpdateProductStatus.feature
Labels: back-end, karate-test, test, Sprint 5

#297 Integration tests on tag and language repositories
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/language/repository/LanguageRepositoryIT.java
  code/orders-boot/src/test/java/com/academy/orders/boot/infrastructure/tag/repository/TagRepositoryIT.java
Labels: back-end, test, Sprint 5

#302 Added required javadoc
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/ChangeAccountStatusUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/CheckAccountIdUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/CreateUserAccountUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/GetAccountDetailsUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/account/usecase/GetAllUsersUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/repository/CartItemImageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/CreateCartItemByUserUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/DeleteProductFromCartUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/GetCartItemsUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/cart/usecase/SetCartItemQuantityUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/language/repository/LanguageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderImageRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/repository/OrderRepository.java
  code/orders-domain/src/main/java/com/academy/orders/domain/order/usecase/GetOrderByIdUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/CreateProductUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/ExtractNameFromUrlUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetAllProductsUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetManagerProductsUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetProductByIdUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/GetProductDetailsByIdUseCase.java
  code/orders-domain/src/main/java/com/academy/orders/domain/product/usecase/UpdateProductUseCase.java
Labels: documentation, back-end, Sprint 5
